### ISSUE TITLE
tflite model 

### ISSUE THREAD

**Issue by azazadev** [Kazuhito00/NARUTO-HandSignDetection#6]
thanks for this great project !!!
any idea how I can convert this Yolo model to tflite ? I have try some tools but not able to make it work ?

**Comment by Kazuhito00** [comment]
Hello.
What tools have you tried?
Since the YOLOX model in this repository has not been modified in particular, it can be converted to TFLite (excluding integer quantization) by the following steps.
1. Convert ONNX to TensorFlow format (*.pb) using onnx-tf
2. Convert to TFLite format using TensorFlow's TFLiteConverter

**Comment by azazadev** [comment]
Hello

I'm using this [https://github.com/motokimura/yolox-ti-lite_tflite](url) and I have this error, so I copy your model inside docker container and run the command onnx2tf ( I'm on MAC M1 )

root@84cbc2070b75:/# onnx2tf -i yolox_nano.onnx
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:560] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1986] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
qemu: uncaught target signal 6 (Aborted) - core dumped


I have also try this [https://lindevs.com/convert-onnx-format-to-tensorflow-2-model](url)

but I got this error

ule>
    from keras.utils import tf_utils
ImportError: cannot import name 'tf_utils' from 'keras.utils'

please if you are able to convert this create separate branch with the tflite model

**Comment by azazadev** [comment]
I'm able to convert this model by using other laptop ( ubuntu ) :), Thanks @Kazuhito00 for your help
now I will check the generated tflite file

**Comment by azazadev** [comment]
@Kazuhito00 I'm facing other issue to make this work, I’m new to machine learning it will be appreciated if you could help me to have the tflite model with simple example of python code that can read this model and parse one image to predict score

**Comment by Kazuhito00** [comment]
This repository does not support tflite inference.

Please refer to the script below.
However, if you use onnx2tf to convert the model, the input shape may be different, so you may need to modify the script.
https://github.com/Kazuhito00/YOLOX-ONNX-TFLite-Sample-Private/blob/main/sample_tflite.py
