### ISSUE TITLE
Extract score and class_id

### ISSUE THREAD

**Issue by azazadev** [Kazuhito00/NARUTO-HandSignDetection#7]
Hi @Kazuhito00 , finally I'm able to convert the model to tflite and with python it's working fine, 
now  I'm trying to do the same with java, so processing new model working fine but I'm not able to process the result

as result I have array like this :

```
index 0 : [1.4157819747924805, 2.1544673442840576, ...... ] : size = 7098

index 1 : [1.805556058883667, 1.946408987045288, ........ ] : size = 7098

index 2 : [1.0974576473236084, 1.980888843536377, ....... ] : size = 7098
..
...
index 20 : [0.0024664357770234, 0.007526415400207, ...... ] : size = 7098
```

I have try to convert the python code of method [_postprocess](https://github.com/Kazuhito00/NARUTO-HandSignDetection/blob/48ddd9ff74a0b468cd8ed85ba9773f47936b6b01/model/yolox/yolox_onnx.py#L90) to java but it's complex, can you please help to optimize this _postprocess method to only return score and class_id ? no need for bboxes

Thanks for your help !

**Comment by Kazuhito00** [comment]
This repository does not support Java.
